#--------------------- DB ----------------------
# DB Connection with the uri (host)
client: "mongodb://localhost:27017/"

# db name
db: "watchara"

# db collection
col: "test"


#--------------------- Dataframe Instantiation ----------------------
# Dataframe columns list
order: ["Epoch","X", "Y", "Z"]
rename: ["Timestamp","acc_x", "acc_y", "acc_z"]


#--------------------- Dataset Local Storage ----------------------
# dataset location
data_path: "C:/Users/user/miniconda3/envs/myenv/datasett"
# single data instance location path to experiment with the data engineering process and visualization
single_instance_path: "C:/Users/user/miniconda3/envs/myenv/first_test.csv"


#--------------------- Data Engineering ----------------------
# sliding window algorithm parameters
sliding_window:
  ws: 50
  overlap: 25
  w_type: "hann"
  w_center: True
  print_stats: True

# window to handle for visualization purposes
x_number: 5

# filtering parameterization
filter:
  order: 2
  wn: 0.3
  type: "lowpass"


#--------------------- $ Data Preparation ----------------------
# Dimensionality reduction
PCA:
  n_comp: 3


#--------------------- Learning ----------------------
# Classifier - Statistical
classifier:
  SVC:
    C: 1
    kernel: "rbf"
    gamma: 0.01
  # classifier 2
    # put your other Statistical-related classifier params here
  # classifier 3
    # put your other Statistical-related classifier params here

# Parameter Grid for Fine-tuning, for instance, a Grid Search classifier
fine_tune:
  param_grid: [
    {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
    {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
   ]
  cv: 5
  verbose: 1

# Classifier - Neural Network
fit:
  epochs: 100
  batch: 64
  verbose: "auto"